# language: shell
# os: windows
# branches:
#   only:
#     - main
# script:
#   - .\uup_download_windows.cmd
# before_deploy:
#   - git config --local user.name "Your Name"
#   - git config --local user.email "Your Email"
#   - git tag "windows-11-$(date +'%Y%m%d%H%M%S')"
# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file_glob: true
#   file: ./*.iso
#   skip_cleanup: true
language: shell
os: windows
script:
  - travis_wait ./uup_download_windows.cmd
before_deploy:
  - iso_name=$(ls /*.iso)
  - version_build=${iso_name/windows_11_uup_/}
  - version_build=${version_build/.iso/}
deploy:
  provider: releases
  api_key: $MY_TOKEN
  file: /*.iso
  tag_name: $version_build
  name: "Windows 11 UUP $version_build"
