name: Clean workflow runs

on:
  # schedule:
  #   - cron: '0 0 * * *' # run every day at midnight
  workflow_dispatch: # run manually from the Actions tab

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history and tags
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.2.1
        with:
          token: ${{ secrets.MY_TOKEN }}
          save_period: 0 # save runs for 7 days
          save_min_runs_number: 5 # save at least 5 runs
      - name: Delete releases and tags
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: true # keep the latest release and tag
          delete_tags: true # delete the corresponding tags as well
          token: ${{ secrets.MY_TOKEN }}