name: Download Windows ISO

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: download-windows-iso

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run uup_download_windows.cmd
      run: sudo ./uup_download_linux.sh
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows_11.iso
        path: ./*.iso
