name: UUP Dump

on:
  # push:
  #   # branches:
  #   #   - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run uup_download_windows.cmd
      run: |
        move * C:\
        cd C:\
        .\*.cmd
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows_11.iso
        path: C:\*.iso
    - name: Get version and build number from ISO file name
      id: get_version_build
      run: |
        $iso_name = (Get-ChildItem C:\*.iso).Name
        $version_build = $iso_name -replace "windows_11_uup_", "" -replace ".iso", ""
        echo "::set-output name=version_build::$version_build"
    - name: Create a release with ISO artifact
      uses: ncipollo/release-action@v1
      with:
        artifacts: "C:/*.iso"
        tag: ${{ steps.get_version_build.outputs.version_build }}
        name: "Windows 11 UUP ${{ steps.get_version_build.outputs.version_build }}"
        token: ${{ secrets.MY_TOKEN }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Run uup_download_windows.cmd
#       run: |
#         sudo apt-get install cabextract wimtools chntpw genisoimage
#     - name: Build Windows
#       run: |
#         sudo sh uup_download_linux.sh
#     - name: Upload ISO artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: windows_11.iso
#         path: ./*.iso
