name: UUP Adguard

on:
  # push:
  #   # branches:
  #   #   - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run uup_download_windows.cmd
      run: |
        move * C:\
        cd C:\adguard\
        .\*.cmd
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: windows_11_adguard.iso
        path: C:\adguard\*.iso
    # - name: Get version and build number from ISO file name
    #   id: get_version_build
    #   run: |
    #     $iso_name = (Get-ChildItem C:\adguard\*.iso).Name
    #     $version_build = $iso_name -replace "windows_11_adguard_", "" -replace ".iso", ""
    #     echo "::set-output name=version_build::$version_build"
    # - name: Create a release with ISO artifact
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "C:/adguard/*.iso"
    #     tag: ${{ steps.get_version_build.outputs.version_build }}
    #     name: "Windows 11 Adguard ${{ steps.get_version_build.outputs.version_build }}"
    #     token: ${{ secrets.MY_TOKEN }}
